name: 'README Workflow Dispatch'

on:
  schedule:
    - cron: "0 3 1 * *" # Run at 3AM on first of the month

jobs:
  update_cd_badge:
    name: "Update Continuous Delivery README Badge"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update README.md
        run: |
          sed -i -E "s/(label=CD%20)\(.*?\)/\1($(date +%B)%20$(date +%Y))/" README.md
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git commit -am "Renewing README Badges"
          git push