name: '[Reusable] Blob Trigger Pytest'

on:
  workflow_call:
    inputs:
      ACT_MODE:
        description: |
          For running Github Action Workflows locally with Nektos act
        required: true
        type: boolean
      markers:
        description: |
          PyTest Markers to select specific tests to work within Github Action Workflows
        required: true
        type: string
    
    secrets:
      GOOGLE_IMPERSONATE_SERVICE_ACCOUNT_EMAIL:
        description: |
          Google Cloud Service Account Impersonator for authentication
        required: true
      GOOGLE_PROJECT:
        description: |
          Google Cloud Project ID
        required: true
      GOOGLE_WORKLOAD_IDENTITY_PROVIDER:
        description: |
          Google Cloud Workload Identity Federation Provider Member ID
        required: false
      GOOGLE_OAUTH_ACCESS_TOKEN:
        description: |
          Google Cloud OAauth2 Access Token
        required: false
      TF_API_TOKEN:
        description: |
          Terraform.io Access Token
        required: true

#Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read

env:
  GOOGLE_PROJECT: "${{ secrets.GCP_PROJECT }}"
  GOOGLE_OAUTH_ACCESS_TOKEN: "${{ secrets.GOOGLE_OAUTH_ACCESS_TOKEN }}"

jobs:
  terraform-output:
    name: Terraform Output
    runs-on: ubuntu-latest
    
    defaults:
        run:
          working-directory: "./test"
    
    outputs:
      INPUT_BUCKET: "${{ steps.tf-raw.outputs.INPUT_BUCKET }}"
      OUTPUT_BUCKET: "${{ steps.tf-raw.outputs.OUTPUT_BUCKET }}"
      SERVICE_ACCOUNT: "${{ steps.tf-raw.outputs.SERVICE_ACCOUNT}}"

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
    
    # Install the latest version of the Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        terraform_wrapper: false
    
    - name: terraform init
      run: terraform init

    - name: terraform raw output
      id: tf-raw
      run: |
        echo "INPUT_BUCKET=$(terraform output -raw trigger_bucket_name)
        OUTPUT_BUCKET=$(terraform output -raw results_bucket_name)
        SERVICE_ACCOUNT=$(terraform output -raw service_account)" >> $GITHUB_OUTPUT
  
  terraform-test:
    name: Terraform Test
    needs: [ terraform-output ]
    runs-on: ubuntu-latest
    env:
        INPUT_BUCKET: ${{ needs.terraform-output.outputs.INPUT_BUCKET }}
        OUTPUT_BUCKET: ${{ needs.terraform-output.outputs.OUTPUT_BUCKET }}
    
    defaults:
      run:
        working-directory: "./test/unit_test"
    
    steps:
      - uses: actions/checkout@v4

      - name: Configure GCP Credentials - Github Runner
        uses: 'google-github-actions/auth@v2'
        if: ${{ !inputs.ACT_MODE }}
        with:
          service_account: "${{ needs.terraform-output.outputs.SERVICE_ACCOUNT }}"
          workload_identity_provider: "${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}"
          create_credentials_file: true
        
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
                  
      # Install pip and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest google-auth gcsfs uuid
      
      - name: Test with pytest
        run: |
          pytest -m "${{ inputs.markers }}" \
            --doctest-modules \
            --junitxml=junit/test-results.xml
              
      - name: Upload pytest test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: junit/test-results.xml